controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

app_api:
    resource: ../../src/Controller/Api/
    type:     annotation
    prefix: api/
